### ISSUE TITLE
Hover Effect on Navbar Links

### ISSUE THREAD

**Issue by TechSpiritSS** [LWM-Community/LWM-Community-Web-Page#16]
I changed the Navbar Links as shown in the gif using CSS only
![ZHAqRFXjNL](https://user-images.githubusercontent.com/76687985/135857069-878c35ba-2ecc-42d5-8616-9bdd60bf9038.gif)

**Comment by TechSpiritSS** [comment]
can I work on this?

**Comment by ikramulkayes** [comment]
Yes, you can!
You have been assigned.
